name: 'Generate CLOC Badge'
description: 'An action to generate a lines-of-code badge using cloc and Shields.io'
author: 'Nihar Basisth <nihar.basisth@agrijod.in>'
inputs:
  github_token:
    description: 'GitHub token for authentication'
    required: true
  branch:
    description: 'The branch to commit the badge to'
    required: false
    default: 'gh-pages'
outputs: {}
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'code'
  color: 'blue'
